question_answer_task:
  description: >
    Make sure you answer all of the customers questions and concerns.
  expected output: >
    simple responses to the customers questions and concerns relating to the products

retrieval_task:
  description: >
    Make sure you retrieve the information from the database and provide it to the customer.
  expected output: >
    The information that the customer requested.